export const avaliacoes = [
  {
    id: 1,
    cafeId: 3,
    userId: 1,
    data: '2026-07-10',
    notas: {
      fragrance: 8,
      flavor: 7,
      aftertaste: 8,
      acidity: 7,
      body: 8,
      uniformity: 10,
      cleanCup: 10,
      sweetness: 9,
      balance: 7,
      overall: 8,
    },
    pontuacaoTotal: 82,
    classificacao: 'Muito Bom',
    comentario: 'Café com notas florais marcantes, acidez cítrica e corpo médio.',
  },
  {
    id: 2,
    cafeId: 5,
    userId: 2,
    data: '2026-07-10',
    notas: {
      fragrance: 7,
      flavor: 8,
      aftertaste: 7,
      acidity: 8,
      body: 9,
      uniformity: 10,
      cleanCup: 10,
      sweetness: 8,
      balance: 8,
      overall: 8,
    },
    pontuacaoTotal: 83,
    classificacao: 'Muito Bom',
    comentario: 'Corpo encorpado, doçura natural elevada e finalização prolongada.',
  },
  {
    id: 3,
    cafeId: 1,
    userId: 3,
    data: '2026-07-11',
    notas: {
      fragrance: 9,
      flavor: 9,
      aftertaste: 8,
      acidity: 9,
      body: 8,
      uniformity: 10,
      cleanCup: 10,
      sweetness: 10,
      balance: 9,
      overall: 9,
    },
    pontuacaoTotal: 91,
    classificacao: 'Excelente',
    comentario: 'Aroma intenso e complexo, acidez vibrante e aftertaste prolongado.',
  },
  {
    id: 4,
    cafeId: 7,
    userId: 4,
    data: '2026-07-11',
    notas: {
      fragrance: 6,
      flavor: 6,
      aftertaste: 6,
      acidity: 7,
      body: 7,
      uniformity: 10,
      cleanCup: 10,
      sweetness: 8,
      balance: 6,
      overall: 6,
    },
    pontuacaoTotal: 72,
    classificacao: 'Regular',
    comentario: 'Café simples, acidez moderada e corpo leve. Sem grandes destaques.',
  },
  {
    id: 5,
    cafeId: 2,
    userId: 1,
    data: '2026-07-12',
    notas: {
      fragrance: 8,
      flavor: 8,
      aftertaste: 8,
      acidity: 8,
      body: 7,
      uniformity: 10,
      cleanCup: 10,
      sweetness: 9,
      balance: 8,
      overall: 8,
    },
    pontuacaoTotal: 84,
    classificacao: 'Muito Bom',
    comentario: 'Equilibrado, com notas de caramelo e finalização limpa.',
  },
  {
    id: 6,
    cafeId: 10,
    userId: 2,
    data: '2026-07-12',
    notas: {
      fragrance: 9,
      flavor: 9,
      aftertaste: 9,
      acidity: 8,
      body: 8,
      uniformity: 10,
      cleanCup: 10,
      sweetness: 9,
      balance: 9,
      overall: 9,
    },
    pontuacaoTotal: 90,
    classificacao: 'Excelente',
    comentario: 'Acidez cítrica elegante, corpo aveludado e doçura persistente.',
  },
  {
    id: 7,
    cafeId: 4,
    userId: 3,
    data: '2026-07-12',
    notas: {
      fragrance: 7,
      flavor: 7,
      aftertaste: 7,
      acidity: 6,
      body: 8,
      uniformity: 10,
      cleanCup: 10,
      sweetness: 8,
      balance: 7,
      overall: 7,
    },
    pontuacaoTotal: 77,
    classificacao: 'Bom',
    comentario: 'Café agradável, corpo médio e acidez suave.',
  },
  {
    id: 8,
    cafeId: 9,
    userId: 4,
    data: '2026-07-13',
    notas: {
      fragrance: 8,
      flavor: 9,
      aftertaste: 8,
      acidity: 9,
      body: 7,
      uniformity: 10,
      cleanCup: 10,
      sweetness: 9,
      balance: 8,
      overall: 9,
    },
    pontuacaoTotal: 87,
    classificacao: 'Muito Bom',
    comentario: 'Notas frutadas intensas, acidez viva e finalização adocicada.',
  },
  {
    id: 9,
    cafeId: 6,
    userId: 1,
    data: '2026-07-13',
    notas: {
      fragrance: 7,
      flavor: 7,
      aftertaste: 7,
      acidity: 8,
      body: 8,
      uniformity: 10,
      cleanCup: 10,
      sweetness: 8,
      balance: 7,
      overall: 7,
    },
    pontuacaoTotal: 79,
    classificacao: 'Bom',
    comentario: 'Café tradicional, boa acidez e corpo moderado.',
  },
  {
    id: 10,
    cafeId: 12,
    userId: 2,
    data: '2026-07-13',
    notas: {
      fragrance: 9,
      flavor: 10,
      aftertaste: 9,
      acidity: 9,
      body: 9,
      uniformity: 10,
      cleanCup: 10,
      sweetness: 10,
      balance: 9,
      overall: 10,
    },
    pontuacaoTotal: 95,
    classificacao: 'Excelente',
    comentario: 'Café excepcional! Notas complexas, acidez brilhante e corpo aveludado.',
  },
  {
    id: 11,
    cafeId: 8,
    userId: 3,
    data: '2026-07-14',
    notas: {
      fragrance: 8,
      flavor: 8,
      aftertaste: 7,
      acidity: 7,
      body: 8,
      uniformity: 10,
      cleanCup: 10,
      sweetness: 9,
      balance: 8,
      overall: 8,
    },
    pontuacaoTotal: 83,
    classificacao: 'Muito Bom',
    comentario: 'Bom equilíbrio, notas de chocolate e finalização limpa.',
  },
  {
    id: 12,
    cafeId: 14,
    userId: 4,
    data: '2026-07-14',
    notas: {
      fragrance: 6,
      flavor: 5,
      aftertaste: 6,
      acidity: 6,
      body: 6,
      uniformity: 10,
      cleanCup: 10,
      sweetness: 7,
      balance: 6,
      overall: 5,
    },
    pontuacaoTotal: 67,
    classificacao: 'Regular',
    comentario: 'Café abaixo da média, acidez baixa e corpo aguado.',
  },
  {
    id: 13,
    cafeId: 11,
    userId: 1,
    data: '2026-07-14',
    notas: {
      fragrance: 8,
      flavor: 8,
      aftertaste: 8,
      acidity: 7,
      body: 7,
      uniformity: 10,
      cleanCup: 10,
      sweetness: 8,
      balance: 8,
      overall: 8,
    },
    pontuacaoTotal: 82,
    classificacao: 'Muito Bom',
    comentario: 'Café macio, notas de amendôas e acidez suave.',
  },
  {
    id: 14,
    cafeId: 15,
    userId: 2,
    data: '2026-07-15',
    notas: {
      fragrance: 7,
      flavor: 7,
      aftertaste: 7,
      acidity: 8,
      body: 7,
      uniformity: 10,
      cleanCup: 10,
      sweetness: 8,
      balance: 7,
      overall: 7,
    },
    pontuacaoTotal: 78,
    classificacao: 'Bom',
    comentario: 'Café honesto, acidez média e finalização curta.',
  },
  {
    id: 15,
    cafeId: 13,
    userId: 3,
    data: '2026-07-15',
    notas: {
      fragrance: 9,
      flavor: 8,
      aftertaste: 9,
      acidity: 8,
      body: 9,
      uniformity: 10,
      cleanCup: 10,
      sweetness: 9,
      balance: 8,
      overall: 9,
    },
    pontuacaoTotal: 89,
    classificacao: 'Muito Bom',
    comentario: 'Corpo encorpado, notas de frutas escuras e finalização prolongada.',
  },
  {
    id: 16,
    cafeId: 17,
    userId: 4,
    data: '2026-07-15',
    notas: {
      fragrance: 8,
      flavor: 8,
      aftertaste: 8,
      acidity: 9,
      body: 8,
      uniformity: 10,
      cleanCup: 10,
      sweetness: 9,
      balance: 8,
      overall: 8,
    },
    pontuacaoTotal: 86,
    classificacao: 'Muito Bom',
    comentario: 'Acidez marcante, corpo médio e notas caramelizadas.',
  },
  {
    id: 17,
    cafeId: 16,
    userId: 1,
    data: '2026-07-16',
    notas: {
      fragrance: 7,
      flavor: 6,
      aftertaste: 6,
      acidity: 7,
      body: 7,
      uniformity: 10,
      cleanCup: 10,
      sweetness: 7,
      balance: 6,
      overall: 6,
    },
    pontuacaoTotal: 72,
    classificacao: 'Regular',
    comentario: 'Café sem grande complexidade, perfil reto e simples.',
  },
  {
    id: 18,
    cafeId: 19,
    userId: 2,
    data: '2026-07-16',
    notas: {
      fragrance: 9,
      flavor: 9,
      aftertaste: 9,
      acidity: 9,
      body: 8,
      uniformity: 10,
      cleanCup: 10,
      sweetness: 10,
      balance: 9,
      overall: 9,
    },
    pontuacaoTotal: 92,
    classificacao: 'Excelente',
    comentario: 'Café aromático, doçura natural intensa e acidez equilibrada.',
  },
  {
    id: 19,
    cafeId: 18,
    userId: 3,
    data: '2026-07-16',
    notas: {
      fragrance: 8,
      flavor: 7,
      aftertaste: 7,
      acidity: 7,
      body: 8,
      uniformity: 10,
      cleanCup: 10,
      sweetness: 8,
      balance: 7,
      overall: 7,
    },
    pontuacaoTotal: 79,
    classificacao: 'Bom',
    comentario: 'Café equilibrado, notas terrosas e finalização média.',
  },
  {
    id: 20,
    cafeId: 20,
    userId: 4,
    data: '2026-07-16',
    notas: {
      fragrance: 8,
      flavor: 8,
      aftertaste: 8,
      acidity: 8,
      body: 8,
      uniformity: 10,
      cleanCup: 10,
      sweetness: 9,
      balance: 8,
      overall: 8,
    },
    pontuacaoTotal: 85,
    classificacao: 'Muito Bom',
    comentario: 'Café bem equilibrado, notas florais e finalização limpa.',
  },
  {
    id: 21,
    cafeId: 4,
    userId: 1,
    data: '2026-07-14',
    notas: {"fragrance": 6, "flavor": 6, "aftertaste": 6, "acidity": 10, "body": 5, "uniformity": 10, "cleanCup": 10, "sweetness": 9, "balance": 5, "overall": 9},
    pontuacaoTotal: 76,
    classificacao: 'Bom',
    comentario: 'Notas de amêndoas e nozes.',
  },
  {
    id: 22,
    cafeId: 2,
    userId: 1,
    data: '2026-07-11',
    notas: {"fragrance": 6, "flavor": 6, "aftertaste": 9, "acidity": 9, "body": 5, "uniformity": 10, "cleanCup": 8, "sweetness": 10, "balance": 10, "overall": 10},
    pontuacaoTotal: 83,
    classificacao: 'Muito Bom',
    comentario: 'Notas terrosas e encorpado.',
  },
  {
    id: 23,
    cafeId: 14,
    userId: 2,
    data: '2026-07-17',
    notas: {"fragrance": 9, "flavor": 7, "aftertaste": 5, "acidity": 6, "body": 10, "uniformity": 9, "cleanCup": 9, "sweetness": 7, "balance": 6, "overall": 6},
    pontuacaoTotal: 74,
    classificacao: 'Regular',
    comentario: 'Perfil limpo e adocicado.',
  },
  {
    id: 24,
    cafeId: 4,
    userId: 1,
    data: '2026-07-16',
    notas: {"fragrance": 5, "flavor": 7, "aftertaste": 7, "acidity": 9, "body": 7, "uniformity": 8, "cleanCup": 10, "sweetness": 8, "balance": 9, "overall": 5},
    pontuacaoTotal: 75,
    classificacao: 'Bom',
    comentario: 'Corpo leve e suave.',
  },
  {
    id: 25,
    cafeId: 3,
    userId: 3,
    data: '2026-07-19',
    notas: {"fragrance": 7, "flavor": 9, "aftertaste": 6, "acidity": 10, "body": 5, "uniformity": 8, "cleanCup": 10, "sweetness": 6, "balance": 7, "overall": 5},
    pontuacaoTotal: 73,
    classificacao: 'Regular',
    comentario: 'Acidez vibrante e refrescante.',
  },
  {
    id: 26,
    cafeId: 4,
    userId: 4,
    data: '2026-07-14',
    notas: {"fragrance": 8, "flavor": 10, "aftertaste": 7, "acidity": 6, "body": 7, "uniformity": 9, "cleanCup": 8, "sweetness": 10, "balance": 7, "overall": 10},
    pontuacaoTotal: 82,
    classificacao: 'Muito Bom',
    comentario: 'Doçura natural elevada.',
  },
  {
    id: 27,
    cafeId: 20,
    userId: 2,
    data: '2026-07-18',
    notas: {"fragrance": 10, "flavor": 6, "aftertaste": 6, "acidity": 8, "body": 8, "uniformity": 9, "cleanCup": 10, "sweetness": 10, "balance": 9, "overall": 6},
    pontuacaoTotal: 82,
    classificacao: 'Muito Bom',
    comentario: 'Perfil limpo e adocicado.',
  },
  {
    id: 28,
    cafeId: 2,
    userId: 2,
    data: '2026-07-10',
    notas: {"fragrance": 7, "flavor": 8, "aftertaste": 7, "acidity": 5, "body": 6, "uniformity": 10, "cleanCup": 10, "sweetness": 7, "balance": 6, "overall": 10},
    pontuacaoTotal: 76,
    classificacao: 'Bom',
    comentario: 'Café simples sem grandes destaques.',
  },
  {
    id: 29,
    cafeId: 13,
    userId: 4,
    data: '2026-07-12',
    notas: {"fragrance": 7, "flavor": 6, "aftertaste": 6, "acidity": 10, "body": 9, "uniformity": 10, "cleanCup": 9, "sweetness": 10, "balance": 9, "overall": 8},
    pontuacaoTotal: 84,
    classificacao: 'Muito Bom',
    comentario: 'Doçura persistente e agradável.',
  },
  {
    id: 30,
    cafeId: 13,
    userId: 3,
    data: '2026-07-13',
    notas: {"fragrance": 6, "flavor": 9, "aftertaste": 8, "acidity": 5, "body": 5, "uniformity": 8, "cleanCup": 8, "sweetness": 10, "balance": 6, "overall": 10},
    pontuacaoTotal: 75,
    classificacao: 'Bom',
    comentario: 'Notas de amêndoas e nozes.',
  },
  {
    id: 31,
    cafeId: 20,
    userId: 1,
    data: '2026-07-16',
    notas: {"fragrance": 8, "flavor": 9, "aftertaste": 8, "acidity": 9, "body": 7, "uniformity": 10, "cleanCup": 8, "sweetness": 10, "balance": 10, "overall": 5},
    pontuacaoTotal: 84,
    classificacao: 'Muito Bom',
    comentario: 'Notas terrosas e encorpado.',
  },
  {
    id: 32,
    cafeId: 9,
    userId: 3,
    data: '2026-07-11',
    notas: {"fragrance": 7, "flavor": 8, "aftertaste": 6, "acidity": 8, "body": 5, "uniformity": 10, "cleanCup": 10, "sweetness": 7, "balance": 9, "overall": 6},
    pontuacaoTotal: 76,
    classificacao: 'Bom',
    comentario: 'Acidez moderada, corpo regular.',
  },
  {
    id: 33,
    cafeId: 4,
    userId: 3,
    data: '2026-07-18',
    notas: {"fragrance": 9, "flavor": 6, "aftertaste": 6, "acidity": 7, "body": 6, "uniformity": 10, "cleanCup": 10, "sweetness": 5, "balance": 9, "overall": 7},
    pontuacaoTotal: 75,
    classificacao: 'Bom',
    comentario: 'Café simples sem grandes destaques.',
  },
  {
    id: 34,
    cafeId: 1,
    userId: 1,
    data: '2026-07-15',
    notas: {"fragrance": 7, "flavor": 6, "aftertaste": 5, "acidity": 6, "body": 9, "uniformity": 8, "cleanCup": 8, "sweetness": 10, "balance": 8, "overall": 5},
    pontuacaoTotal: 72,
    classificacao: 'Regular',
    comentario: 'Notas terrosas e encorpado.',
  },
  {
    id: 35,
    cafeId: 5,
    userId: 2,
    data: '2026-07-17',
    notas: {"fragrance": 9, "flavor": 6, "aftertaste": 7, "acidity": 9, "body": 9, "uniformity": 9, "cleanCup": 8, "sweetness": 9, "balance": 10, "overall": 10},
    pontuacaoTotal: 86,
    classificacao: 'Muito Bom',
    comentario: 'Notas de caramelo e chocolate.',
  },
  {
    id: 36,
    cafeId: 10,
    userId: 4,
    data: '2026-07-15',
    notas: {"fragrance": 8, "flavor": 9, "aftertaste": 8, "acidity": 5, "body": 6, "uniformity": 8, "cleanCup": 8, "sweetness": 7, "balance": 5, "overall": 9},
    pontuacaoTotal: 73,
    classificacao: 'Regular',
    comentario: 'Notas terrosas e encorpado.',
  },
  {
    id: 37,
    cafeId: 8,
    userId: 2,
    data: '2026-07-10',
    notas: {"fragrance": 5, "flavor": 10, "aftertaste": 10, "acidity": 5, "body": 6, "uniformity": 8, "cleanCup": 8, "sweetness": 7, "balance": 5, "overall": 9},
    pontuacaoTotal: 73,
    classificacao: 'Regular',
    comentario: 'Acidez vibrante e refrescante.',
  },
  {
    id: 38,
    cafeId: 9,
    userId: 4,
    data: '2026-07-13',
    notas: {"fragrance": 9, "flavor": 6, "aftertaste": 10, "acidity": 9, "body": 9, "uniformity": 9, "cleanCup": 8, "sweetness": 8, "balance": 8, "overall": 6},
    pontuacaoTotal: 82,
    classificacao: 'Muito Bom',
    comentario: 'Finalização prolongada e limpa.',
  },
  {
    id: 39,
    cafeId: 4,
    userId: 4,
    data: '2026-07-15',
    notas: {"fragrance": 8, "flavor": 8, "aftertaste": 8, "acidity": 10, "body": 5, "uniformity": 10, "cleanCup": 10, "sweetness": 10, "balance": 5, "overall": 5},
    pontuacaoTotal: 79,
    classificacao: 'Bom',
    comentario: 'Corpo leve e suave.',
  },
  {
    id: 40,
    cafeId: 11,
    userId: 1,
    data: '2026-07-13',
    notas: {"fragrance": 6, "flavor": 6, "aftertaste": 9, "acidity": 8, "body": 6, "uniformity": 9, "cleanCup": 8, "sweetness": 7, "balance": 8, "overall": 6},
    pontuacaoTotal: 73,
    classificacao: 'Regular',
    comentario: 'Doçura natural elevada.',
  },
  {
    id: 41,
    cafeId: 15,
    userId: 1,
    data: '2026-07-10',
    notas: {"fragrance": 10, "flavor": 9, "aftertaste": 5, "acidity": 5, "body": 6, "uniformity": 8, "cleanCup": 9, "sweetness": 8, "balance": 8, "overall": 6},
    pontuacaoTotal: 74,
    classificacao: 'Regular',
    comentario: 'Corpo leve e suave.',
  },
  {
    id: 42,
    cafeId: 2,
    userId: 2,
    data: '2026-07-16',
    notas: {"fragrance": 5, "flavor": 8, "aftertaste": 7, "acidity": 8, "body": 7, "uniformity": 9, "cleanCup": 10, "sweetness": 10, "balance": 9, "overall": 10},
    pontuacaoTotal: 83,
    classificacao: 'Muito Bom',
    comentario: 'Café simples sem grandes destaques.',
  },
  {
    id: 43,
    cafeId: 5,
    userId: 2,
    data: '2026-07-14',
    notas: {"fragrance": 6, "flavor": 5, "aftertaste": 9, "acidity": 10, "body": 9, "uniformity": 8, "cleanCup": 10, "sweetness": 7, "balance": 5, "overall": 5},
    pontuacaoTotal: 74,
    classificacao: 'Regular',
    comentario: 'Doçura persistente e agradável.',
  },
  {
    id: 44,
    cafeId: 16,
    userId: 2,
    data: '2026-07-10',
    notas: {"fragrance": 9, "flavor": 5, "aftertaste": 6, "acidity": 5, "body": 9, "uniformity": 8, "cleanCup": 10, "sweetness": 6, "balance": 8, "overall": 5},
    pontuacaoTotal: 71,
    classificacao: 'Regular',
    comentario: 'Doçura persistente e agradável.',
  },
  {
    id: 45,
    cafeId: 8,
    userId: 1,
    data: '2026-07-19',
    notas: {"fragrance": 5, "flavor": 8, "aftertaste": 10, "acidity": 9, "body": 9, "uniformity": 10, "cleanCup": 9, "sweetness": 7, "balance": 6, "overall": 10},
    pontuacaoTotal: 83,
    classificacao: 'Muito Bom',
    comentario: 'Perfil limpo e adocicado.',
  },
  {
    id: 46,
    cafeId: 8,
    userId: 3,
    data: '2026-07-16',
    notas: {"fragrance": 6, "flavor": 10, "aftertaste": 10, "acidity": 7, "body": 8, "uniformity": 9, "cleanCup": 8, "sweetness": 5, "balance": 8, "overall": 9},
    pontuacaoTotal: 80,
    classificacao: 'Muito Bom',
    comentario: 'Doçura persistente e agradável.',
  },
  {
    id: 47,
    cafeId: 4,
    userId: 1,
    data: '2026-07-18',
    notas: {"fragrance": 6, "flavor": 9, "aftertaste": 7, "acidity": 6, "body": 7, "uniformity": 8, "cleanCup": 8, "sweetness": 7, "balance": 7, "overall": 6},
    pontuacaoTotal: 71,
    classificacao: 'Regular',
    comentario: 'Finalização curta e seca.',
  },
  {
    id: 48,
    cafeId: 18,
    userId: 3,
    data: '2026-07-19',
    notas: {"fragrance": 10, "flavor": 9, "aftertaste": 5, "acidity": 10, "body": 9, "uniformity": 9, "cleanCup": 10, "sweetness": 5, "balance": 6, "overall": 7},
    pontuacaoTotal: 80,
    classificacao: 'Muito Bom',
    comentario: 'Finalização prolongada e limpa.',
  },
  {
    id: 49,
    cafeId: 4,
    userId: 2,
    data: '2026-07-14',
    notas: {"fragrance": 7, "flavor": 9, "aftertaste": 6, "acidity": 10, "body": 7, "uniformity": 8, "cleanCup": 10, "sweetness": 10, "balance": 7, "overall": 9},
    pontuacaoTotal: 83,
    classificacao: 'Muito Bom',
    comentario: 'Café simples sem grandes destaques.',
  },
  {
    id: 50,
    cafeId: 9,
    userId: 1,
    data: '2026-07-11',
    notas: {"fragrance": 10, "flavor": 8, "aftertaste": 7, "acidity": 5, "body": 5, "uniformity": 9, "cleanCup": 8, "sweetness": 10, "balance": 7, "overall": 6},
    pontuacaoTotal: 75,
    classificacao: 'Bom',
    comentario: 'Finalização curta e seca.',
  },
  {
    id: 51,
    cafeId: 18,
    userId: 4,
    data: '2026-07-18',
    notas: {"fragrance": 5, "flavor": 5, "aftertaste": 5, "acidity": 10, "body": 6, "uniformity": 10, "cleanCup": 8, "sweetness": 7, "balance": 9, "overall": 9},
    pontuacaoTotal: 74,
    classificacao: 'Regular',
    comentario: 'Aroma intenso e complexo.',
  },
  {
    id: 52,
    cafeId: 14,
    userId: 2,
    data: '2026-07-10',
    notas: {"fragrance": 7, "flavor": 7, "aftertaste": 5, "acidity": 7, "body": 6, "uniformity": 10, "cleanCup": 8, "sweetness": 10, "balance": 5, "overall": 7},
    pontuacaoTotal: 72,
    classificacao: 'Regular',
    comentario: 'Notas terrosas e encorpado.',
  },
  {
    id: 53,
    cafeId: 14,
    userId: 2,
    data: '2026-07-13',
    notas: {"fragrance": 6, "flavor": 6, "aftertaste": 8, "acidity": 5, "body": 6, "uniformity": 10, "cleanCup": 9, "sweetness": 8, "balance": 10, "overall": 10},
    pontuacaoTotal: 78,
    classificacao: 'Bom',
    comentario: 'Acidez vibrante e refrescante.',
  },
  {
    id: 54,
    cafeId: 9,
    userId: 2,
    data: '2026-07-11',
    notas: {"fragrance": 8, "flavor": 5, "aftertaste": 8, "acidity": 6, "body": 6, "uniformity": 9, "cleanCup": 9, "sweetness": 7, "balance": 6, "overall": 6},
    pontuacaoTotal: 70,
    classificacao: 'Regular',
    comentario: 'Café com notas florais marcantes.',
  },
  {
    id: 55,
    cafeId: 7,
    userId: 4,
    data: '2026-07-15',
    notas: {"fragrance": 7, "flavor": 5, "aftertaste": 7, "acidity": 7, "body": 10, "uniformity": 10, "cleanCup": 9, "sweetness": 10, "balance": 9, "overall": 7},
    pontuacaoTotal: 81,
    classificacao: 'Muito Bom',
    comentario: 'Café com notas florais marcantes.',
  },
  {
    id: 56,
    cafeId: 4,
    userId: 3,
    data: '2026-07-12',
    notas: {"fragrance": 9, "flavor": 7, "aftertaste": 5, "acidity": 5, "body": 9, "uniformity": 9, "cleanCup": 9, "sweetness": 10, "balance": 7, "overall": 8},
    pontuacaoTotal: 78,
    classificacao: 'Bom',
    comentario: 'Café abaixo da média esperada.',
  },
  {
    id: 57,
    cafeId: 17,
    userId: 1,
    data: '2026-07-16',
    notas: {"fragrance": 9, "flavor": 6, "aftertaste": 7, "acidity": 5, "body": 10, "uniformity": 9, "cleanCup": 8, "sweetness": 9, "balance": 9, "overall": 10},
    pontuacaoTotal: 82,
    classificacao: 'Muito Bom',
    comentario: 'Notas de caramelo e chocolate.',
  },
  {
    id: 58,
    cafeId: 12,
    userId: 4,
    data: '2026-07-11',
    notas: {"fragrance": 10, "flavor": 7, "aftertaste": 9, "acidity": 7, "body": 10, "uniformity": 8, "cleanCup": 10, "sweetness": 7, "balance": 9, "overall": 7},
    pontuacaoTotal: 84,
    classificacao: 'Muito Bom',
    comentario: 'Notas de amêndoas e nozes.',
  },
  {
    id: 59,
    cafeId: 11,
    userId: 4,
    data: '2026-07-14',
    notas: {"fragrance": 9, "flavor": 6, "aftertaste": 6, "acidity": 8, "body": 10, "uniformity": 9, "cleanCup": 10, "sweetness": 10, "balance": 6, "overall": 9},
    pontuacaoTotal: 83,
    classificacao: 'Muito Bom',
    comentario: 'Doçura persistente e agradável.',
  },
  {
    id: 60,
    cafeId: 10,
    userId: 4,
    data: '2026-07-18',
    notas: {"fragrance": 5, "flavor": 7, "aftertaste": 7, "acidity": 6, "body": 8, "uniformity": 10, "cleanCup": 10, "sweetness": 10, "balance": 7, "overall": 8},
    pontuacaoTotal: 78,
    classificacao: 'Bom',
    comentario: 'Finalização curta e seca.',
  },
  {
    id: 61,
    cafeId: 15,
    userId: 2,
    data: '2026-07-18',
    notas: {"fragrance": 8, "flavor": 10, "aftertaste": 6, "acidity": 10, "body": 5, "uniformity": 9, "cleanCup": 10, "sweetness": 10, "balance": 10, "overall": 9},
    pontuacaoTotal: 87,
    classificacao: 'Muito Bom',
    comentario: 'Perfil limpo e adocicado.',
  },
  {
    id: 62,
    cafeId: 3,
    userId: 2,
    data: '2026-07-14',
    notas: {"fragrance": 6, "flavor": 6, "aftertaste": 6, "acidity": 5, "body": 5, "uniformity": 8, "cleanCup": 9, "sweetness": 9, "balance": 5, "overall": 8},
    pontuacaoTotal: 67,
    classificacao: 'Regular',
    comentario: 'Notas de amêndoas e nozes.',
  },
  {
    id: 63,
    cafeId: 19,
    userId: 2,
    data: '2026-07-16',
    notas: {"fragrance": 8, "flavor": 8, "aftertaste": 6, "acidity": 6, "body": 10, "uniformity": 10, "cleanCup": 8, "sweetness": 5, "balance": 8, "overall": 6},
    pontuacaoTotal: 75,
    classificacao: 'Bom',
    comentario: 'Corpo encorpado e aveludado.',
  },
  {
    id: 64,
    cafeId: 17,
    userId: 4,
    data: '2026-07-10',
    notas: {"fragrance": 9, "flavor": 6, "aftertaste": 5, "acidity": 8, "body": 6, "uniformity": 9, "cleanCup": 10, "sweetness": 9, "balance": 9, "overall": 9},
    pontuacaoTotal: 80,
    classificacao: 'Muito Bom',
    comentario: 'Perfil limpo e adocicado.',
  },
  {
    id: 65,
    cafeId: 15,
    userId: 4,
    data: '2026-07-18',
    notas: {"fragrance": 8, "flavor": 6, "aftertaste": 10, "acidity": 8, "body": 8, "uniformity": 9, "cleanCup": 8, "sweetness": 10, "balance": 7, "overall": 9},
    pontuacaoTotal: 83,
    classificacao: 'Muito Bom',
    comentario: 'Café simples sem grandes destaques.',
  },
  {
    id: 66,
    cafeId: 8,
    userId: 3,
    data: '2026-07-17',
    notas: {"fragrance": 5, "flavor": 10, "aftertaste": 7, "acidity": 6, "body": 7, "uniformity": 9, "cleanCup": 9, "sweetness": 9, "balance": 5, "overall": 6},
    pontuacaoTotal: 73,
    classificacao: 'Regular',
    comentario: 'Aroma intenso e complexo.',
  },
  {
    id: 67,
    cafeId: 8,
    userId: 4,
    data: '2026-07-12',
    notas: {"fragrance": 10, "flavor": 6, "aftertaste": 5, "acidity": 8, "body": 8, "uniformity": 9, "cleanCup": 10, "sweetness": 8, "balance": 8, "overall": 5},
    pontuacaoTotal: 77,
    classificacao: 'Bom',
    comentario: 'Notas de caramelo e chocolate.',
  },
  {
    id: 68,
    cafeId: 14,
    userId: 4,
    data: '2026-07-19',
    notas: {"fragrance": 10, "flavor": 5, "aftertaste": 9, "acidity": 8, "body": 8, "uniformity": 8, "cleanCup": 9, "sweetness": 7, "balance": 8, "overall": 8},
    pontuacaoTotal: 80,
    classificacao: 'Muito Bom',
    comentario: 'Notas terrosas e encorpado.',
  },
  {
    id: 69,
    cafeId: 18,
    userId: 2,
    data: '2026-07-17',
    notas: {"fragrance": 6, "flavor": 7, "aftertaste": 8, "acidity": 8, "body": 5, "uniformity": 9, "cleanCup": 9, "sweetness": 10, "balance": 10, "overall": 8},
    pontuacaoTotal: 80,
    classificacao: 'Muito Bom',
    comentario: 'Corpo encorpado e aveludado.',
  },
  {
    id: 70,
    cafeId: 15,
    userId: 2,
    data: '2026-07-19',
    notas: {"fragrance": 9, "flavor": 5, "aftertaste": 8, "acidity": 9, "body": 9, "uniformity": 10, "cleanCup": 8, "sweetness": 5, "balance": 10, "overall": 8},
    pontuacaoTotal: 81,
    classificacao: 'Muito Bom',
    comentario: 'Aroma intenso e complexo.',
  },
  {
    id: 71,
    cafeId: 15,
    userId: 2,
    data: '2026-07-10',
    notas: {"fragrance": 7, "flavor": 8, "aftertaste": 7, "acidity": 6, "body": 8, "uniformity": 9, "cleanCup": 9, "sweetness": 8, "balance": 7, "overall": 8},
    pontuacaoTotal: 77,
    classificacao: 'Bom',
    comentario: 'Café equilibrado e macio.',
  },
  {
    id: 72,
    cafeId: 3,
    userId: 4,
    data: '2026-07-10',
    notas: {"fragrance": 10, "flavor": 9, "aftertaste": 5, "acidity": 7, "body": 6, "uniformity": 10, "cleanCup": 8, "sweetness": 10, "balance": 5, "overall": 5},
    pontuacaoTotal: 75,
    classificacao: 'Bom',
    comentario: 'Acidez vibrante e refrescante.',
  },
  {
    id: 73,
    cafeId: 7,
    userId: 1,
    data: '2026-07-19',
    notas: {"fragrance": 6, "flavor": 6, "aftertaste": 6, "acidity": 8, "body": 10, "uniformity": 8, "cleanCup": 10, "sweetness": 6, "balance": 8, "overall": 10},
    pontuacaoTotal: 78,
    classificacao: 'Bom',
    comentario: 'Café equilibrado e macio.',
  },
  {
    id: 74,
    cafeId: 12,
    userId: 2,
    data: '2026-07-19',
    notas: {"fragrance": 9, "flavor": 10, "aftertaste": 10, "acidity": 5, "body": 6, "uniformity": 9, "cleanCup": 8, "sweetness": 9, "balance": 5, "overall": 7},
    pontuacaoTotal: 78,
    classificacao: 'Bom',
    comentario: 'Doçura persistente e agradável.',
  },
  {
    id: 75,
    cafeId: 13,
    userId: 4,
    data: '2026-07-13',
    notas: {"fragrance": 5, "flavor": 9, "aftertaste": 10, "acidity": 10, "body": 6, "uniformity": 8, "cleanCup": 10, "sweetness": 7, "balance": 10, "overall": 9},
    pontuacaoTotal: 84,
    classificacao: 'Muito Bom',
    comentario: 'Finalização prolongada e limpa.',
  },
  {
    id: 76,
    cafeId: 19,
    userId: 1,
    data: '2026-07-15',
    notas: {"fragrance": 9, "flavor": 8, "aftertaste": 10, "acidity": 7, "body": 5, "uniformity": 10, "cleanCup": 10, "sweetness": 7, "balance": 5, "overall": 8},
    pontuacaoTotal: 79,
    classificacao: 'Bom',
    comentario: 'Café simples sem grandes destaques.',
  },
  {
    id: 77,
    cafeId: 4,
    userId: 4,
    data: '2026-07-15',
    notas: {"fragrance": 10, "flavor": 8, "aftertaste": 10, "acidity": 6, "body": 8, "uniformity": 8, "cleanCup": 10, "sweetness": 9, "balance": 10, "overall": 7},
    pontuacaoTotal: 86,
    classificacao: 'Muito Bom',
    comentario: 'Café abaixo da média esperada.',
  },
  {
    id: 78,
    cafeId: 18,
    userId: 4,
    data: '2026-07-17',
    notas: {"fragrance": 8, "flavor": 10, "aftertaste": 9, "acidity": 7, "body": 7, "uniformity": 8, "cleanCup": 8, "sweetness": 7, "balance": 8, "overall": 6},
    pontuacaoTotal: 78,
    classificacao: 'Bom',
    comentario: 'Finalização curta e seca.',
  },
  {
    id: 79,
    cafeId: 19,
    userId: 4,
    data: '2026-07-15',
    notas: {"fragrance": 5, "flavor": 8, "aftertaste": 7, "acidity": 6, "body": 8, "uniformity": 8, "cleanCup": 9, "sweetness": 7, "balance": 7, "overall": 7},
    pontuacaoTotal: 72,
    classificacao: 'Regular',
    comentario: 'Café abaixo da média esperada.',
  },
  {
    id: 80,
    cafeId: 9,
    userId: 1,
    data: '2026-07-18',
    notas: {"fragrance": 6, "flavor": 5, "aftertaste": 6, "acidity": 10, "body": 8, "uniformity": 9, "cleanCup": 10, "sweetness": 6, "balance": 10, "overall": 8},
    pontuacaoTotal: 78,
    classificacao: 'Bom',
    comentario: 'Café simples sem grandes destaques.',
  },
  {
    id: 81,
    cafeId: 15,
    userId: 1,
    data: '2026-07-11',
    notas: {"fragrance": 7, "flavor": 6, "aftertaste": 8, "acidity": 10, "body": 6, "uniformity": 9, "cleanCup": 10, "sweetness": 9, "balance": 7, "overall": 8},
    pontuacaoTotal: 80,
    classificacao: 'Muito Bom',
    comentario: 'Notas terrosas e encorpado.',
  },
  {
    id: 82,
    cafeId: 17,
    userId: 3,
    data: '2026-07-16',
    notas: {"fragrance": 10, "flavor": 9, "aftertaste": 7, "acidity": 7, "body": 10, "uniformity": 9, "cleanCup": 9, "sweetness": 7, "balance": 7, "overall": 6},
    pontuacaoTotal: 81,
    classificacao: 'Muito Bom',
    comentario: 'Finalização prolongada e limpa.',
  },
  {
    id: 83,
    cafeId: 7,
    userId: 3,
    data: '2026-07-11',
    notas: {"fragrance": 10, "flavor": 9, "aftertaste": 10, "acidity": 6, "body": 6, "uniformity": 8, "cleanCup": 10, "sweetness": 8, "balance": 7, "overall": 10},
    pontuacaoTotal: 84,
    classificacao: 'Muito Bom',
    comentario: 'Doçura persistente e agradável.',
  },
  {
    id: 84,
    cafeId: 17,
    userId: 3,
    data: '2026-07-11',
    notas: {"fragrance": 6, "flavor": 7, "aftertaste": 6, "acidity": 7, "body": 6, "uniformity": 9, "cleanCup": 8, "sweetness": 10, "balance": 9, "overall": 6},
    pontuacaoTotal: 74,
    classificacao: 'Regular',
    comentario: 'Café equilibrado e macio.',
  },
  {
    id: 85,
    cafeId: 2,
    userId: 1,
    data: '2026-07-18',
    notas: {"fragrance": 7, "flavor": 10, "aftertaste": 6, "acidity": 10, "body": 8, "uniformity": 8, "cleanCup": 8, "sweetness": 9, "balance": 7, "overall": 8},
    pontuacaoTotal: 81,
    classificacao: 'Muito Bom',
    comentario: 'Café simples sem grandes destaques.',
  },
  {
    id: 86,
    cafeId: 15,
    userId: 3,
    data: '2026-07-12',
    notas: {"fragrance": 5, "flavor": 7, "aftertaste": 8, "acidity": 5, "body": 5, "uniformity": 9, "cleanCup": 9, "sweetness": 5, "balance": 9, "overall": 10},
    pontuacaoTotal: 72,
    classificacao: 'Regular',
    comentario: 'Acidez cítrica e corpo médio.',
  },
  {
    id: 87,
    cafeId: 5,
    userId: 2,
    data: '2026-07-19',
    notas: {"fragrance": 7, "flavor": 5, "aftertaste": 6, "acidity": 5, "body": 9, "uniformity": 9, "cleanCup": 10, "sweetness": 9, "balance": 9, "overall": 6},
    pontuacaoTotal: 75,
    classificacao: 'Bom',
    comentario: 'Acidez moderada, corpo regular.',
  },
  {
    id: 88,
    cafeId: 13,
    userId: 4,
    data: '2026-07-17',
    notas: {"fragrance": 7, "flavor": 9, "aftertaste": 8, "acidity": 7, "body": 9, "uniformity": 10, "cleanCup": 8, "sweetness": 9, "balance": 10, "overall": 5},
    pontuacaoTotal: 82,
    classificacao: 'Muito Bom',
    comentario: 'Notas de caramelo e chocolate.',
  },
  {
    id: 89,
    cafeId: 7,
    userId: 3,
    data: '2026-07-11',
    notas: {"fragrance": 6, "flavor": 6, "aftertaste": 6, "acidity": 9, "body": 5, "uniformity": 8, "cleanCup": 8, "sweetness": 8, "balance": 8, "overall": 10},
    pontuacaoTotal: 74,
    classificacao: 'Regular',
    comentario: 'Café abaixo da média esperada.',
  },
  {
    id: 90,
    cafeId: 16,
    userId: 3,
    data: '2026-07-10',
    notas: {"fragrance": 6, "flavor": 7, "aftertaste": 10, "acidity": 7, "body": 10, "uniformity": 9, "cleanCup": 8, "sweetness": 10, "balance": 6, "overall": 7},
    pontuacaoTotal: 80,
    classificacao: 'Muito Bom',
    comentario: 'Doçura persistente e agradável.',
  },
  {
    id: 91,
    cafeId: 7,
    userId: 4,
    data: '2026-07-11',
    notas: {"fragrance": 9, "flavor": 6, "aftertaste": 10, "acidity": 6, "body": 7, "uniformity": 8, "cleanCup": 8, "sweetness": 5, "balance": 6, "overall": 7},
    pontuacaoTotal: 72,
    classificacao: 'Regular',
    comentario: 'Café abaixo da média esperada.',
  },
  {
    id: 92,
    cafeId: 19,
    userId: 3,
    data: '2026-07-17',
    notas: {"fragrance": 5, "flavor": 8, "aftertaste": 10, "acidity": 7, "body": 10, "uniformity": 9, "cleanCup": 9, "sweetness": 9, "balance": 9, "overall": 8},
    pontuacaoTotal: 84,
    classificacao: 'Muito Bom',
    comentario: 'Finalização curta e seca.',
  },
  {
    id: 93,
    cafeId: 3,
    userId: 1,
    data: '2026-07-16',
    notas: {"fragrance": 10, "flavor": 7, "aftertaste": 9, "acidity": 7, "body": 5, "uniformity": 8, "cleanCup": 8, "sweetness": 10, "balance": 9, "overall": 9},
    pontuacaoTotal: 82,
    classificacao: 'Muito Bom',
    comentario: 'Café com notas florais marcantes.',
  },
  {
    id: 94,
    cafeId: 9,
    userId: 1,
    data: '2026-07-12',
    notas: {"fragrance": 8, "flavor": 9, "aftertaste": 10, "acidity": 8, "body": 7, "uniformity": 8, "cleanCup": 10, "sweetness": 8, "balance": 10, "overall": 8},
    pontuacaoTotal: 86,
    classificacao: 'Muito Bom',
    comentario: 'Doçura natural elevada.',
  },
  {
    id: 95,
    cafeId: 16,
    userId: 3,
    data: '2026-07-16',
    notas: {"fragrance": 7, "flavor": 7, "aftertaste": 10, "acidity": 5, "body": 6, "uniformity": 9, "cleanCup": 9, "sweetness": 10, "balance": 8, "overall": 7},
    pontuacaoTotal: 78,
    classificacao: 'Bom',
    comentario: 'Corpo leve e suave.',
  },
  {
    id: 96,
    cafeId: 18,
    userId: 1,
    data: '2026-07-17',
    notas: {"fragrance": 5, "flavor": 7, "aftertaste": 7, "acidity": 7, "body": 5, "uniformity": 9, "cleanCup": 10, "sweetness": 5, "balance": 10, "overall": 9},
    pontuacaoTotal: 74,
    classificacao: 'Regular',
    comentario: 'Finalização curta e seca.',
  },
  {
    id: 97,
    cafeId: 14,
    userId: 1,
    data: '2026-07-13',
    notas: {"fragrance": 9, "flavor": 7, "aftertaste": 9, "acidity": 8, "body": 10, "uniformity": 9, "cleanCup": 8, "sweetness": 6, "balance": 7, "overall": 9},
    pontuacaoTotal: 82,
    classificacao: 'Muito Bom',
    comentario: 'Aroma intenso e complexo.',
  },
  {
    id: 98,
    cafeId: 10,
    userId: 4,
    data: '2026-07-17',
    notas: {"fragrance": 5, "flavor": 5, "aftertaste": 10, "acidity": 9, "body": 6, "uniformity": 10, "cleanCup": 8, "sweetness": 7, "balance": 9, "overall": 5},
    pontuacaoTotal: 74,
    classificacao: 'Regular',
    comentario: 'Notas terrosas e encorpado.',
  },
  {
    id: 99,
    cafeId: 14,
    userId: 1,
    data: '2026-07-13',
    notas: {"fragrance": 5, "flavor": 8, "aftertaste": 5, "acidity": 10, "body": 6, "uniformity": 9, "cleanCup": 10, "sweetness": 7, "balance": 9, "overall": 10},
    pontuacaoTotal: 79,
    classificacao: 'Bom',
    comentario: 'Café equilibrado e macio.',
  },
  {
    id: 100,
    cafeId: 14,
    userId: 4,
    data: '2026-07-17',
    notas: {"fragrance": 6, "flavor": 8, "aftertaste": 9, "acidity": 6, "body": 8, "uniformity": 8, "cleanCup": 10, "sweetness": 9, "balance": 10, "overall": 6},
    pontuacaoTotal: 80,
    classificacao: 'Muito Bom',
    comentario: 'Doçura natural elevada.',
  },
  {
    id: 101,
    cafeId: 9,
    userId: 4,
    data: '2026-07-15',
    notas: {"fragrance": 9, "flavor": 7, "aftertaste": 5, "acidity": 7, "body": 10, "uniformity": 9, "cleanCup": 10, "sweetness": 9, "balance": 10, "overall": 8},
    pontuacaoTotal: 84,
    classificacao: 'Muito Bom',
    comentario: 'Aroma intenso e complexo.',
  },
  {
    id: 102,
    cafeId: 15,
    userId: 4,
    data: '2026-07-15',
    notas: {"fragrance": 7, "flavor": 9, "aftertaste": 9, "acidity": 8, "body": 8, "uniformity": 9, "cleanCup": 8, "sweetness": 10, "balance": 6, "overall": 9},
    pontuacaoTotal: 83,
    classificacao: 'Muito Bom',
    comentario: 'Corpo leve e suave.',
  },
  {
    id: 103,
    cafeId: 8,
    userId: 4,
    data: '2026-07-10',
    notas: {"fragrance": 7, "flavor": 10, "aftertaste": 8, "acidity": 10, "body": 8, "uniformity": 9, "cleanCup": 10, "sweetness": 10, "balance": 6, "overall": 8},
    pontuacaoTotal: 86,
    classificacao: 'Muito Bom',
    comentario: 'Acidez cítrica e corpo médio.',
  },
  {
    id: 104,
    cafeId: 5,
    userId: 3,
    data: '2026-07-11',
    notas: {"fragrance": 8, "flavor": 5, "aftertaste": 9, "acidity": 8, "body": 5, "uniformity": 10, "cleanCup": 8, "sweetness": 8, "balance": 10, "overall": 6},
    pontuacaoTotal: 77,
    classificacao: 'Bom',
    comentario: 'Doçura natural elevada.',
  },
  {
    id: 105,
    cafeId: 16,
    userId: 3,
    data: '2026-07-15',
    notas: {"fragrance": 9, "flavor": 10, "aftertaste": 8, "acidity": 10, "body": 5, "uniformity": 9, "cleanCup": 10, "sweetness": 9, "balance": 8, "overall": 7},
    pontuacaoTotal: 85,
    classificacao: 'Muito Bom',
    comentario: 'Café simples sem grandes destaques.',
  },
  {
    id: 106,
    cafeId: 18,
    userId: 1,
    data: '2026-07-19',
    notas: {"fragrance": 5, "flavor": 6, "aftertaste": 10, "acidity": 10, "body": 7, "uniformity": 8, "cleanCup": 10, "sweetness": 5, "balance": 8, "overall": 5},
    pontuacaoTotal: 74,
    classificacao: 'Regular',
    comentario: 'Finalização prolongada e limpa.',
  },
  {
    id: 107,
    cafeId: 15,
    userId: 2,
    data: '2026-07-14',
    notas: {"fragrance": 5, "flavor": 5, "aftertaste": 7, "acidity": 5, "body": 7, "uniformity": 9, "cleanCup": 9, "sweetness": 8, "balance": 6, "overall": 6},
    pontuacaoTotal: 67,
    classificacao: 'Regular',
    comentario: 'Acidez moderada, corpo regular.',
  },
  {
    id: 108,
    cafeId: 14,
    userId: 2,
    data: '2026-07-12',
    notas: {"fragrance": 6, "flavor": 5, "aftertaste": 9, "acidity": 8, "body": 9, "uniformity": 10, "cleanCup": 8, "sweetness": 8, "balance": 9, "overall": 6},
    pontuacaoTotal: 78,
    classificacao: 'Bom',
    comentario: 'Acidez vibrante e refrescante.',
  },
  {
    id: 109,
    cafeId: 15,
    userId: 3,
    data: '2026-07-17',
    notas: {"fragrance": 7, "flavor": 10, "aftertaste": 5, "acidity": 8, "body": 7, "uniformity": 10, "cleanCup": 10, "sweetness": 6, "balance": 5, "overall": 8},
    pontuacaoTotal: 76,
    classificacao: 'Bom',
    comentario: 'Acidez brilhante e elegante.',
  },
  {
    id: 110,
    cafeId: 19,
    userId: 3,
    data: '2026-07-16',
    notas: {"fragrance": 10, "flavor": 7, "aftertaste": 8, "acidity": 7, "body": 6, "uniformity": 9, "cleanCup": 9, "sweetness": 5, "balance": 6, "overall": 8},
    pontuacaoTotal: 75,
    classificacao: 'Bom',
    comentario: 'Doçura persistente e agradável.',
  },
]

export default avaliacoes
