export const coffees = [
  {
    id: 1,
    nome: 'Bourbon Amarelo',
    produtor: 'Fazenda Boa Vista',
    avaliacoes: 0,
    notas: {},
    pontuacaoTotal: 0,
  },
  {
    id: 2,
    nome: 'Arara',
    produtor: 'Sítio das Flores',
    avaliacoes: 0,
    notas: {},
    pontuacaoTotal: 0,
  },
  {
    id: 3,
    nome: 'Geisha',
    produtor: 'Fazenda Horizonte',
    avaliacoes: 0,
    notas: {},
    pontuacaoTotal: 0,
  },
  {
    id: 4,
    nome: 'Catuaí Vermelho',
    produtor: 'Café do Vale',
    avaliacoes: 0,
    notas: {},
    pontuacaoTotal: 0,
  },
  {
    id: 5,
    nome: 'Catucaí 2SL',
    produtor: 'Fazenda Primavera',
    avaliacoes: 0,
    notas: {},
    pontuacaoTotal: 0,
  },
  {
    id: 6,
    nome: 'Mundo Novo',
    produtor: 'Santa Clara',
    avaliacoes: 0,
    notas: {},
    pontuacaoTotal: 0,
  },
  {
    id: 7,
    nome: 'Topázio',
    produtor: 'Serra Azul',
    avaliacoes: 0,
    notas: {},
    pontuacaoTotal: 0,
  },
  {
    id: 8,
    nome: 'Acauã',
    produtor: 'Fazenda Aurora',
    avaliacoes: 0,
    notas: {},
    pontuacaoTotal: 0,
  },
  {
    id: 9,
    nome: 'Icatu',
    produtor: 'Sítio Verdejante',
    avaliacoes: 0,
    notas: {},
    pontuacaoTotal: 0,
  },
  {
    id: 10,
    nome: 'Rubi',
    produtor: 'Fazenda Bela Vista',
    avaliacoes: 0,
    notas: {},
    pontuacaoTotal: 0,
  },
  {
    id: 11,
    nome: 'Catuai Amarelo',
    produtor: 'Fazenda Nova Esperança',
    avaliacoes: 0,
    notas: {},
    pontuacaoTotal: 0,
  },
  {
    id: 12,
    nome: 'SL28',
    produtor: 'Fazenda Esperança',
    avaliacoes: 0,
    notas: {},
    pontuacaoTotal: 0,
  },
  {
    id: 13,
    nome: 'Laurina',
    produtor: 'Recanto do Café',
    avaliacoes: 0,
    notas: {},
    pontuacaoTotal: 0,
  },
  {
    id: 14,
    nome: 'Maragogipe',
    produtor: 'Alto da Serra',
    avaliacoes: 0,
    notas: {},
    pontuacaoTotal: 0,
  },
  {
    id: 15,
    nome: 'Pacas',
    produtor: 'Fazenda Santa Luzia',
    avaliacoes: 0,
    notas: {},
    pontuacaoTotal: 0,
  },
  {
    id: 16,
    nome: 'Typica',
    produtor: 'Montanhas do Sul',
    avaliacoes: 0,
    notas: {},
    pontuacaoTotal: 0,
  },
  {
    id: 17,
    nome: 'Bourbon Vermelho',
    produtor: 'Fazenda Ouro Verde',
    avaliacoes: 0,
    notas: {},
    pontuacaoTotal: 0,
  },
  {
    id: 18,
    nome: 'Caturra',
    produtor: 'Sítio Bela Vista',
    avaliacoes: 0,
    notas: {},
    pontuacaoTotal: 0,
  },
  {
    id: 19,
    nome: 'Mokka',
    produtor: 'Fazenda Colina',
    avaliacoes: 0,
    notas: {},
    pontuacaoTotal: 0,
  },
  {
    id: 20,
    nome: 'Villa Sarchi',
    produtor: 'Vale do Cedro',
    avaliacoes: 0,
    notas: {},
    pontuacaoTotal: 0,
  },
]
