export const cafes = [
  { id: 1, nome: 'Bourbon Amarelo', produtor: 'Fazenda Boa Vista' },
  { id: 2, nome: 'Arara', produtor: 'Sítio das Flores' },
  { id: 3, nome: 'Geisha', produtor: 'Fazenda Horizonte' },
  { id: 4, nome: 'Catuaí Vermelho', produtor: 'Café do Vale' },
  { id: 5, nome: 'Catucaí 2SL', produtor: 'Fazenda Primavera' },
  { id: 6, nome: 'Mundo Novo', produtor: 'Santa Clara' },
  { id: 7, nome: 'Topázio', produtor: 'Serra Azul' },
  { id: 8, nome: 'Acauã', produtor: 'Fazenda Aurora' },
  { id: 9, nome: 'Obatã', produtor: 'Vale Verde' },
  { id: 10, nome: 'Icatu Amarelo', produtor: 'Monte Belo' },
  { id: 11, nome: 'Pacamara', produtor: 'Serra Dourada' },
  { id: 12, nome: 'SL28', produtor: 'Fazenda Esperança' },
  { id: 13, nome: 'Laurina', produtor: 'Recanto do Café' },
  { id: 14, nome: 'Maragogipe', produtor: 'Alto da Serra' },
  { id: 15, nome: 'Pacas', produtor: 'Fazenda Santa Luzia' },
  { id: 16, nome: 'Typica', produtor: 'Montanhas do Sul' },
  { id: 17, nome: 'Bourbon Vermelho', produtor: 'Fazenda Ouro Verde' },
  { id: 18, nome: 'Caturra', produtor: 'Sítio Bela Vista' },
  { id: 19, nome: 'Mokka', produtor: 'Fazenda Colina' },
  { id: 20, nome: 'Villa Sarchi', produtor: 'Vale do Cedro' },
];
