export const imagensCafes = [
  { id: 1, url: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQgeIa1pgteo_q0_oSB6EWpmqrbT2z9XvHl0geShRwcPQ&s" },
  { id: 2, url: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTJhAT5Pj11WjZz14jCISQzyegjRZzM0AmGkwpDW3bh0g&s=10" },
  { id: 3, url: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRUsu2Fox-KzfdJ0YGok2gGl_GviTMfSHsU-_N1l70iOQ&s=10" },
  { id: 4, url: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRG-EH_71hP1YEF3g86Ildsw1Wo9SQJ1cKZO60nIyrXYA&s" },
  { id: 5, url: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQfeympqSjnmaiL547CyMOCf8YaWc5-d0XYynzvnh9bow&s" },
  { id: 6, url: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRR1gkkVPsEsS8d958n9u4nIzMUCCCabDeryRmhltWssw&s=10" },
  { id: 7, url: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTMDARWPgKQn-Q54m8MaHCg8bExfPCmkfhfJD13jlpENg&s=10" },
  { id: 8, url: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSZWP4NREmuAYh0sYJCUuZi6eqNMX2jUBkPJZ47-_hBpw&s=10" },
  { id: 9, url: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTJhAT5Pj11WjZz14jCISQzyegjRZzM0AmGkwpDW3bh0g&s=10" },
  { id: 10, url: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQgeIa1pgteo_q0_oSB6EWpmqrbT2z9XvHl0geShRwcPQ&s" },
  { id: 11, url: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSZWP4NREmuAYh0sYJCUuZi6eqNMX2jUBkPJZ47-_hBpw&s=10" },
  { id: 12, url: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRUsu2Fox-KzfdJ0YGok2gGl_GviTMfSHsU-_N1l70iOQ&s=10" },
  { id: 13, url: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRR1gkkVPsEsS8d958n9u4nIzMUCCCabDeryRmhltWssw&s=10" },
  { id: 14, url: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQfeympqSjnmaiL547CyMOCf8YaWc5-d0XYynzvnh9bow&s" },
  { id: 15, url: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTMDARWPgKQn-Q54m8MaHCg8bExfPCmkfhfJD13jlpENg&s=10" },
  { id: 16, url: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRG-EH_71hP1YEF3g86Ildsw1Wo9SQJ1cKZO60nIyrXYA&s" },
  { id: 17, url: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQgeIa1pgteo_q0_oSB6EWpmqrbT2z9XvHl0geShRwcPQ&s" },
  { id: 18, url: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRUsu2Fox-KzfdJ0YGok2gGl_GviTMfSHsU-_N1l70iOQ&s=10" },
  { id: 19, url: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSZWP4NREmuAYh0sYJCUuZi6eqNMX2jUBkPJZ47-_hBpw&s=10" },
  { id: 20, url: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTJhAT5Pj11WjZz14jCISQzyegjRZzM0AmGkwpDW3bh0g&s=10" },
]
